### ISSUE TITLE
Exception when package.json lacks a `scripts` property

### ISSUE THREAD

**Issue by adi-works** [jaketrent/npm-ls-scripts#5]
```
C:\Users\XXX\AppData\Roaming\nvm\v7.10.0\node_modules\npm-ls-scripts\lib\ls.js:55
    var scriptNames = Object.keys(pkg.scripts)
                             ^

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C:\Users\XXX\AppData\Roaming\nvm\v7.10.0\node_modules\npm-ls-scripts\lib\ls.js:55:30
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

**Comment by simonua** [comment]
Hi @jaketrent, is there any way one of the two PRs that fix this could be merged and an update released, please? Thank you!

**Comment by adi-works** [comment]
Wouldn't count on it, use this instead:
```
npm run
```
or
```
yarn run
```
That will list all scripts.

**Comment by jaketrent** [comment]
lol, yeah, now npm does this natively. :D

**Comment by matt-harvey** [comment]
@jaketrent I've got some PRs there too, that have been open for some time.

As you say, npm now does this natively.

Perhaps you could either merge, or close the remaining PRs, then mark the repo as archived? That would provide some clarity for anyone who comes across this repo, who hasn't yet realized that npm provides this capability out of the box.
